---
title: "RWorksheet_Salinas#3a"
author: "Salinas, Reysha Marie"
date: "2023-10-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#1
#Based on the above vector LETTERS:


       LETTERS

#a. You need to produce a vector that contains the first 11 letters. 
    
    UPPERCASE <- LETTERS
    first_11 <- LETTERS [1:11] 
    first_11
 
#b. Produce a vector that contains the odd numbered letters.

      odd<- LETTERS
      odd<- LETTERS[seq(1,length (LETTERS), by = 2)]
      odd



#c. Produce a vector that contains the vowels 
      
      vowels <- c("A", "E", "I", "O", "U")
      vowels
 
#or

      LETTERS[c(1,5,9,15,21)]


#Based on the above vector letters:  

#d. Produce a vector that contains the last 5 lowercase letters.

      last5 <- tail(letters, 5)
      last5


#e. Produce a vector that contains letters between 15 to 24 letters in lowercase. 

        lowercase <- letters
        lttr15_to_24 <- lowercase[15:24]
         lttr15_to_24


#2. Create a vector(not a dataframe) with the average temperatures in April for Tuguegarao City, Manila, Iloilo City, Tacloban, Samal Island, and Davao City. The average temperatures in Celcius are 42, 39, 34, 34, 30, and 27 degrees.

#a. What is the R code and its result for creating a character vector for the city/town of Tuguegarao City, Manila, Iloilo City, Tacloban,Samal Island, and Davao City? Name the

      city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
      print(city)

#b. The average temperatures in Celcius are 42, 39, 34, 34, 30, and 27 degrees. Name the object as temp. Write the R code and its output. Numbers should also follow what is in the instruction.
#Write the R code 

     temp <- c(42, 39, 34, 34, 30, 27)
      temp #OUPUT 42 39 34 34 30 27 

#c. Create a dataframe to combine the city and the temp by using ‘data.frame(). 
#What the R code and its result? 

    city_and_temp <- data.frame(city, temp)
    city_and_temp

#OUPUT/RESULT 

             #city temp
#1 Tuguegarao City   42
#2          Manila   39
#3     Iloilo City   34
#4        Tacloban   34
#5    Samal Island   30
#6      Davao City   27


#d. Associate the dataframe you have created in 2.(c) by naming the columns using the names() function. Change the column names by using names() function as City and Temperature. 
#What is the R code and its result? 

        names(city_and_temp) <- c("City", "Temperature" )
        city_and_temp
#OUPUT/RESULT

                #City Temperature
#1 Tuguegarao City          42
#2          Manila          39
#3     Iloilo City          34
#4        Tacloban          34
#5    Samal Island          30
#6      Davao City          27

#e. Print the structure by using str() function. Describe the output.

    str(city_and_temp) 

#Describe the output. 
#'data.frame':	6 obs. of  2 variables:, This shows that the data frame have 6 observation or known as row and 2 colummns.
# $ City       : chr  "Tuguegarao City" "Manila" "Iloilo City" "Tacloban" ... 
#This shows the City column and indicate that it is a character variable. 
#$ Temperature: num  42 39 34 34 30 27 
#This shows the Temperature column and indicate that it is a numeric variable. 

#f. From the answer in d, what is the content of row 3 and row 4 
#What is its R code and its output?


    content<- city_and_temp[3:4,]   
    content

#OUPUT 

         
          #City Temperature
#3 Iloilo City          34 

#4 Tacloban             34

#g. From the answer in d, display the city with highest temperature and the city with the lowest temperature. 
#What is its R code and its output?


#find the lowest indedx

              lowest_temp <- city_and_temp[which.min(city_and_temp$Temperature),]
              lowest_temp

#find the highest index
  
             highest_temp <- city_and_temp[which.max(city_and_temp$Temperature),]
            highest_temp

#OUTPUT, The provided code identifies and retrieves the names of cities that correspond to the lowest and highest temperatures within the data frame.

#2. Create a matrix of one to eight and eleven to fourteen with four columns and three rows.
#a. What will be the R code for the #2 question and its result? 

          matrix <- matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
        matrix
#OUPUT 
#   [,1] [,2] [,3] [,4]
#[1,]    1    4    7   12
#[2,]    2    5    8   13
#[3,]    3    6   11   14 


#b. Multiply the matrix by two. What is its R code and its result? 

      matrixtwo <- matrix * 2
      print(matrixtwo)

#c. What is the content of row 2? What is its R code? 

    matrixtwo[2,]

#d. What will be the R code if you want to display the column 3 and column 4 in row 1 and row 2? What is its output?

    column3and4 <- matrixtwo[1:2, 3:4] #nrow,ncol 

    column3and4 #OUTPUT     [,1] [,2]
                              #[1,]   14   24
                              #[2,]   16   26


#e. What is the R code is you want to display only the columns in 2 and 3, row 3? What is its output?

      matrixtwo [3, 2:3]   

#OUPUT [1] 12 22 

#f. What is the R code is you want to display only the columns 4? What is its output?

      matrixtwo[ ,4] 

#OUPUT  [1] 24 26 28 

#g. Name the rows as isa, dalawa, tatlo and columns as uno, dos, tres, quatro for the matrix that was created in b.‘. 
#What is its R code and corresponding output? 

# Create the matrix with the specified values and dimensions
        
        dimnames(matrixtwo) <- list(c("isa", "dalawa", "tatlo"), c("uno", "dos", "tres", "quatro"))

        matrixtwo

#OUPUT      uno dos tres quatro

      #isa      1   4    7     12
      #dalawa   2   5    8     13
      #tatlo    3   6   11     14

#h. From the original matrix you have created in a, reshape the matrix by assigning a new dimension with dim(). New dimensions should have 2 columns and 6 rows. 
#What will be the R code and its output?


      dim(matrix) <- c(6,2)
      matrix
#OUPUT     [,1] [,2]

    #[1,]    1    7
    #[2,]    2    8
    #[3,]    3   11
    #[4,]    4   12
    #[5,]    5   13
    #[6,]    6   14


#3 An array contains 1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1

#a. Create an array for the above numeric values. Each values will be repeated twice
#What will be the R code if you are to create a three-dimensional array with 4 columns and 2 rows. What will be its output?

      values <- c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)

#twice

      repeated <- rep(values, each = 2)
      array <- array(repeated, dim = c(2, 4, 3))


      array


#OUPUT 
#, ,1
#[,1] [,2] [,3] [,4]
#[1,]    1    2    3    6
#[2,]    1    2    3    6

#, , 2

#[,1] [,2] [,3] [,4]
#[1,]    7    8    9    0
#[2,]    7    8    9    0

#, , 3

#[,1] [,2] [,3] [,4]
#[1,]    3    4    5    1
#[2,]    3    4    5    1


#b. How many dimensions do your array have? My array has three dimensions. 


#c. Name the rows as lowercase letters and columns as uppercase letters starting from the A. The array names should be “1st-Dimensional Array”, “2nd-Dimensional Array”, and “3rd-Dimensional Array”.
#What will be the R codes and its output?


    dimnames(array_data) <- list(
         row_names <- letters[1:2],
        col_names <- LETTERS[1:4], c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array"))
 
      array_data 
 
 
#OUPUT 
#1st-Dimensional Array

#A B C D
#a 1 2 3 6
#b 1 2 3 6

#, , 2nd-Dimensional Array

#A B C D
#a 7 8 9 0
#b 7 8 9 0

#, , 3rd-Dimensional Array

#A B C D
#a 3 4 5 1
#b 3 4 5 1



